[package]
name = "specdown"
version = "1.1.1"
description = "A tool to test markdown files and drive development from documentation."
repository = "https://github.com/specdown/specdown"
readme = "README.md"
license = "Apache-2.0"
authors = [ "Tom Oram <me@tomoram.io>" ]
edition = "2018"
categories = [
  "command-line-utilities",
  "development-tools",
  "development-tools::testing"
]
keywords = [ "markdown", "testing", "bdd", "tdd", "documentation" ]

[dependencies]
clap = "2.33.0"
crossterm = "0.22"
comrak = "0.10.0"
nom = "7"
termdiff = "3.0.0"
strip-ansi-escapes = "0.1.1"
shell-words = "1.0.0"
tempfile = "3.2.0"

[dev-dependencies]
assert_cmd = "2.0.2"
indoc = "1.0.3"
maplit = "1.0.2"
tempfile = "3.2.0"
