[package]
name = "specdown"
version = "1.2.65"
description = "A tool to test markdown files and drive development from documentation."
repository = "https://github.com/specdown/specdown"
readme = "README.md"
license = "Apache-2.0"
authors = [ "Tom Oram <me@tomoram.io>" ]
edition = "2018"
categories = [
  "command-line-utilities",
  "development-tools",
  "development-tools::testing"
]
keywords = [ "markdown", "testing", "bdd", "tdd", "documentation" ]

[dependencies]
clap = { version = "4.3.17", features = ["derive"] }
clap_derive = "4.1.8"
clap_complete_command = "0.5.1"
crossterm = "0.26.1"
comrak = "0.16.0"
nom = "7.1.3"
termdiff = "3.1.2"
strip-ansi-escapes = "0.1.1"
shell-words = "1.1.0"
tempfile = "3.7.0"

[dev-dependencies]
assert_cmd = "2.0.12"
indoc = "2.0.3"
maplit = "1.0.2"
tempfile = "3.7.0"
