[package]
name = "specdown"
version = "1.2.19"
description = "A tool to test markdown files and drive development from documentation."
repository = "https://github.com/specdown/specdown"
readme = "README.md"
license = "Apache-2.0"
authors = [ "Tom Oram <me@tomoram.io>" ]
edition = "2018"
categories = [
  "command-line-utilities",
  "development-tools",
  "development-tools::testing"
]
keywords = [ "markdown", "testing", "bdd", "tdd", "documentation" ]

[dependencies]
clap = { version = "3.2.10", features = ["derive"] }
clap_derive = "3.1.18"
clap_complete_command = "0.3.4"
crossterm = "0.24"
comrak = "0.13.2"
nom = "7"
termdiff = "3.1.0"
strip-ansi-escapes = "0.1.1"
shell-words = "1.1.0"
tempfile = "3.3.0"

[dev-dependencies]
assert_cmd = "2.0.4"
indoc = "1.0.6"
maplit = "1.0.2"
tempfile = "3.3.0"
