[package]
name = "specdown"
version = "0.43.1"
description = "A tool to test markdown files and drive development from documentation."
repository = "https://github.com/specdown/specdown"
readme = "README.md"
license = "Apache-2.0"
authors = [ "Tom Oram <me@tomoram.io>" ]
edition = "2018"
categories = [
  "command-line-utilities",
  "development-tools",
  "development-tools::testing"
]
keywords = [ "markdown", "testing", "bdd", "tdd", "documentation" ]

[dependencies]
clap = "2.33.0"
crossterm = "0.19"
comrak = "0.10.1"
nom = "6"
colored-diff = "0.2.2"
strip-ansi-escapes = "0.1.0"
shell-words = "1.0.0"

[dev-dependencies]
assert_cmd = "1.0.1"
indoc = "1.0"
maplit = "1.0.2"
