[package]
name = "specdown"
version = "0.14.0"
description = "A tool to test markdown files and drive development from documentation."
repository = "https://github.com/specdown/specdown"
readme = "README.md"
license = "Apache-2.0"
license-file = "LICENSE"
authors = [ "Tom Oram <me@tomoram.io>" ]
edition = "2018"
categories = [
  "command-line-utilities",
  "development-tools",
  "development-tools::testing"
]
keywords = [ "markdown", "testing", "bdd", "tdd", "documentation" ]

[dependencies]
clap = "2.33.0"
comrak = "0.7"
nom = "5"

[dev-dependencies]
assert_cmd = "1.0.1"
indoc = "0.3"
maplit = "1.0.2"
