tag_prefix = "v"
from_latest_tag = true
ignore_merge_commits = true
branch_whitelist = ["master"]
pre_bump_hooks = [
    # In the pipeline, this will be created by a preceding job
    "mv ../bumped-files/* ."
]
post_bump_hooks = [
    "git push",
    "git push origin v{{version}}",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "specdown"
owner = "specdown"
