on:
  workflow_call:
    secrets:
      CI_ACCOUNT_SSH_KEY:
        required: false
    inputs:
      download-artifacts:
        type: boolean
        description: Set to "true" if you want all artifacts downloaded before bumping (this is useful if you want to add something to the bump commit from a previous job).
      release-artifacts:
        type: string
        description: An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
        required: false
        default: ''
      version-prefix:
        type: string
        description: Prefix for the version number
        default: 'v'
    outputs:
      current-version:
        description: The current version after the bump
        value: ${{ jobs.tag-version.outputs.current-version }}
      version-was-bumped:
        description: Set to true if the version was bumped
        value: ${{ jobs.tag-version.outputs.version-was-bumped }}

jobs:
  tag-version:
    name: tag-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      current-version: ${{ steps.bump-version.outputs.current-version }}
      version-was-bumped: ${{ steps.bump-version.outputs.version-was-bumped }}
    steps:
      - name: Download all workflow run artifacts
        if: inputs.download-artifacts
        uses: actions/download-artifact@v3

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ssh-key: ${{ secrets.CI_ACCOUNT_SSH_KEY }}
          path: repo-to-release

      - id: bump-version
        uses: armakuni/github-actions/bump-version@v0.10.5
        with:
          working-directory: repo-to-release

  create-release:
    name: create-release
    runs-on: ubuntu-latest
    needs:
      - tag-version
    if: ${{ needs.tag-version.outputs.version-was-bumped == 'true' }}
    steps:
      - name: Download all workflow run artifacts
        if: inputs.download-artifacts && inputs.release-artifacts
        uses: actions/download-artifact@v3

      - run: echo ${{ needs.tag-version.outputs.version-was-bumped }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For the changelog
          fetch-tags: true # For the changelog
          ref: refs/tags/v${{ needs.tag-version.outputs.current-version }}

      - uses: armakuni/github-actions/setup-cocogitto@v0.2.0
        with:
          version: 5.5.0

      - name: Generate Changelog
        run: cog changelog --at ${{ inputs.version-prefix }}${{ needs.tag-version.outputs.current-version }} -t full_hash > GITHUB_CHANGELOG.md

      - run: |
          pwd
          ls -la
          ls -la ..
          ls ../bins/*

      - name: create-github-release
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          artifacts: ${{ inputs.release-artifacts }}
          bodyFile: GITHUB_CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release v${{ needs.tag-version.outputs.current-version }}
          tag: v${{ needs.tag-version.outputs.current-version }}
